### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by YolandaHuitianDiao** [scverse/scirpy#355] opened 2022-07-20 21:35 UTC
### Description of the bug

Installation error on Linux (x86_64 GNU/Linux, 20.04.1-Ubuntu) with python 3.10, in conda virtual environment

The same environment has latest Scanpy installation from conda-forge.

### Minimal reproducible example

```python
conda install -c conda-forge -c bioconda scirpy
```

### The error message produced by the code above

```pytb
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: /
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versionsThe following specifications were found to be incompatible with your system:

  - feature:/linux-64::__glibc==2.31=0
  - feature:|@/linux-64::__glibc==2.31=0

Your installed version is: 2.31
```

**Comment by grst** [comment] 2022-07-21 09:56
Hi @YolandaHuitianDiao,

thanks for reporting this issue.

* Does the same also happen when you try to install scirpy in a clean environment?
* Did you set up the channels as [described on the bioconda website](https://bioconda.github.io/#usage)? I'm not sure if just specifying `-c` gets the channel priorities right.

**Comment by YolandaHuitianDiao** [comment] 2022-07-29 13:39
I tried to install in a clean environment (also py3.10), and set up channels as described on bioconda:
```
(scirpy) ~$ conda config --add channels defaults
Warning: 'defaults' already in 'channels' list, moving to the top
(scirpy) ~$ conda config --add channels bioconda
Warning: 'bioconda' already in 'channels' list, moving to the top
(scirpy) ~$ conda config --add channels conda-forge
Warning: 'conda-forge' already in 'channels' list, moving to the top
(scirpy) ~$ conda config --set channel_priority strict
(scirpy) ~$ conda install -c conda-forge -c bioconda scirpy
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: \
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versionsThe following specifications were found to be incompatible with your system:

  - feature:/linux-64::__glibc==2.31=0
  - python=3.10 -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']

Your installed version is: 2.31

Note that strict channel priority may have removed packages required for satisfiability.

(scirpy) ~$
```

**Comment by grst** [comment] 2022-07-29 13:52
Hi, 

I looked into this. Running with `mamba` gives a much more informative error message: 

```
Encountered problems while solving:
  - package scirpy-0.11.0-pyhdfd78af_0 requires parasail-python, but none of the providers can be installed
```

So the problem is that parasail is not (yet) available for Python 3.10. It is a compiled package, so it needs a separate build for each python version. 

How to solve this? I'm not sure, maybe just rebuilding parasail on bioconda (i.e. submitting a PR that increases the build number) will do. 

In the meanwhile, if you can work with a python 3.9 environment that should also work.

**Comment by grst** [comment] 2022-08-04 11:41
I saw that a parasail version for python 3.10 was uploaded on bioconda two days ago ==> this should work now!

**Comment by grst** [comment] 2022-08-13 17:55
Closing this for now - feel free to reopen if the issue persists.

**Closed by grst** 2022-08-13 17:55 UTC
Labels: bug
