### ISSUE TITLE
Sorting logic in `index_chains()`

### ISSUE THREAD

**Issue by nh3** [scverse/scirpy#493] opened 2024-02-21 11:25 UTC
Currently the default sorting logic ranks chains by:
first, umi_count (duplicate_count), then, read_count (consensus_count), both in descending order.

However, for chains with equal umi_count, would having higher read_count actually reflect lower real world abundance?

Or, would it be possible to expose the `ascending=` option in `ak.argsort()`, e.g. `sort_chains_by=dict(sort_key=(default_value, ascending))` or a separate `ascending=dict(sort_key=ascending)`.

Does this make sense?

**Comment by grst** [comment] 2024-02-21 17:27
Hi, 

thanks for the question. I don't think that the read count for chains with equal UMI count provides any useful information about true abundance. But it's also not worse than random. There are two reasons it's implemented that way: 
 * the sorting gets more reproducible as it doesn't depend on random order in the case of ties
 * the same default sorting keys can be used for datasets that do and don't provide umi counts

You have a point that it's currently not possible to specify whether to sort ascending/descending in the `index_chains` function. I'm a bit wary thought to introduce even more complexity to that function. 

Would something like

```python
adata.obsm["airr"]["sort_key2"] = -adata.obsm["airr"]["sort_key2"] 
ir.pp.index_chains(adata, sort_chains_by = {"sort_key2": float("-inf")})
```
work for you as a workaround?

**Comment by nh3** [comment] 2024-02-22 09:48
Hi @grst,

Thank you for the quick reply. In the context of 10X VDJ sequencing, abundance of reads is largely determined by, on top of UMI abundance, efficiency of PCR amplification and luck of sampling during sequencing. In other words, read count represents number of observations. Unique molecules that require higher number of observations to be found are likely less abundant than those require fewer observations. That's the rationale. In practice, it would affect only a very small subset of cells.

Thank you for the workaround. I can live with that :). Thanks!

**Comment by grst** [comment] 2024-03-04 19:58
Closing because you said you could live with the workaround. Let me know if there are any other issues.

**Closed** 2024-03-04 19:58 UTC
