### ISSUE TITLE
Cant seem to output clonotype information from clonotype network

### ISSUE THREAD

**Issue by adamwoolfe** [scverse/scirpy#336] opened 2022-05-18 10:29 UTC
Hi, great package!

I'm having a few problems outputting specific clonotype clusters once I have visualized the clusters etc. I can do the clustering no problem and you can see the clusters in the attached image.
![clonotype_cluster](https://user-images.githubusercontent.com/48278595/169018102-cb891774-c8c7-43f2-b316-88b4a363e46d.png)

I wanted to output a table of clonotypes for cluster 4 (the biggest one) and I use the code as specified in the tutorial:

```python
adata_concat.obs.loc[adata_concat.obs["cc_aa_alignment"] == "4", :].groupby(
    [
        "IR_VDJ_1_v_call",
        "IR_VDJ_1_j_call",
        "IR_VJ_1_junction_aa",
        "IR_VDJ_1_junction_aa",
        "receptor_subtype",
    ],
    observed=True,
).size().reset_index(name="n_cells")
```

But I get an empty table output. This is strange because if I count the number of cells I should have in that cluster:

```
len(adata_concat.obs.loc[adata_concat.obs["cc_aa_alignment"] == "4", :])
```

the output is 516, not 0.

Any ideas why this isn't working?

**Comment by adamwoolfe** [comment] 2022-05-18 10:30
BTW, this is BCR data not TCR

**Comment by adamwoolfe** [comment] 2022-05-18 10:32
The clustering commands used were:

ir.pp.ir_dist(
    adata_concat,
    metric="alignment",
    sequence="aa",
    cutoff=15,
)

ir.tl.define_clonotype_clusters(
    adata_concat,
    sequence="aa",
    metric="alignment",
    receptor_arms="all",
    dual_ir="any",
    same_v_gene=True,
    key_added="cc_aa_alignment_same_v",
)

ir.tl.clonotype_network(adata_concat, min_cells=3, sequence="aa", metric="alignment")

**Comment by adamwoolfe** [comment] 2022-05-18 19:03
<html>
<body>


is_cell | high_confidence | multi_chain | extra_chains | IR_VJ_1_c_call | IR_VJ_2_c_call | IR_VDJ_1_c_call | IR_VDJ_2_c_call | IR_VJ_1_consensus_count | IR_VJ_2_consensus_count | ... | receptor_type | receptor_subtype | chain_pairing | leiden | clone_id | clone_id_size | cc_aa_alignment_same_v | cc_aa_alignment_same_v_size | cc_aa_alignment | cc_aa_alignment_size
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
True | True | False | [] | IGKC | NaN | NaN | NaN | 4316.0 | NaN | ... | BCR | IGH+IGK | orphan VJ | 3 | 4 | 7.0 | 4 | 13.0 | 4 | 511.0
True | True | False | [] | IGKC | NaN | NaN | NaN | 27222.0 | NaN | ... | BCR | IGH+IGK | orphan VJ | 1 | 11 | 2.0 | 11 | 12.0 | 4 | 511.0
True | True | False | [] | IGKC | NaN | NaN | NaN | 15238.0 | NaN | ... | BCR | IGH+IGK | orphan VJ | 7 | 13 | 1.0 | 13 | 31.0 | 4 | 511.0
True | True | False | [] | IGKC | NaN | NaN | NaN | 14078.0 | NaN | ... | BCR | IGH+IGK | orphan VJ | 12 | 16 | 1.0 | 13 | 31.0 | 4 | 511.0
True | True | False | [] | IGKC | NaN | NaN | NaN | 1826.0 | NaN | ... | BCR | IGH+IGK | orphan VJ | 2 | 18 | 1.0 | 17 | 1.0 | 4 | 511.0

<p style="box-sizing: border-box; margin: 1em 0px 0px; text-align: left; color: rgb(0, 0, 0); font-family: &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">5 rows × 67 columns</p>
</body>
</html>

**Comment by adamwoolfe** [comment] 2022-05-18 19:04
This is the output of the head command.

**Comment by grst** [comment] 2022-05-19 19:58
I think I found it: 

the problem is that one of your grouping columns contains `NaN`s. 

adding `dropna=False` to your `groupby` call should fix it.

**Comment by adamwoolfe** [comment] 2022-05-19 20:37
I used:
adata_concat.obs.loc[adata_concat.obs["cc_aa_alignment"] == "4", :].groupby( [ "IR_VDJ_1_v_call", "IR_VDJ_1_j_call", "IR_VJ_1_junction_aa", "IR_VDJ_1_junction_aa", "receptor_subtype", ], observed=True, dropna=False).size().reset_index(name="n_cells")

and still didnt work :( Table was empty

**Comment by grst** [comment] 2022-05-19 20:38
Ok, then it would be great if you could send me that anndata object!

**Comment by adamwoolfe** [comment] 2022-05-19 21:47
Sure, will do! Im a bit busy rest of this week, but I'll definitely send it to you next week!

**Comment by adamwoolfe** [comment] 2022-05-24 12:29
The Anndata object is 43.5Mb in size, so have provided a link to it:

https://www.transfernow.net/dl/202205248diEOVsN

**Comment by grst** [comment] 2022-05-24 20:13
Seems you hit a bug in pandas: https://github.com/pandas-dev/pandas/pull/46601

`dropna=False` doesn't work properly with categorical columns. 

Installing the pandas version from that pull request solved the issue for me: 

```bash
pip install git+https://github.com/rhshadrach/pandas.git@factorize_na
```

**Comment by adamwoolfe** [comment] 2022-05-25 08:21
Hi, thanks for looking into this. The problem with this solution is that the above version of pandas is a modified version of v1.1.0 (1.1.0.dev0+7912.gca53df0282) and is therefore a pretty old version of pandas. This version is incompatible with other packages which require newer versions of pandas (e.g. anndata 0.8.0 requires pandas>=1.1.1). I'm confused why any of my groupby fields would have Nan as values. Perhaps I need to do some filtering on the dataframe before running scripy to avoid these issues.

**Comment by adamwoolfe** [comment] 2022-05-25 08:36
Also, the installation of the pandas fix didnt change anything for me :(

**Comment by adamwoolfe** [comment] 2022-05-25 11:49
OK, I think the solution is just to create clonotype maps from specific chains, then we wont have the problem of Nans in these fields. Because I did it for all chains, the value for VDJ for a light chain in Nan when the chain is a heavy chain and vice versa when the chain is a light chain for VJ. OK, I understand this part better now. Im glad we found the source of the bug, but there are ways around it!

**Comment by grst** [comment] 2022-05-25 16:39
another hack is to convert columns to `str`, then NaNs will be converted to the string `"nan"`. 
I guess in the next pandas release this will be solved. 

I'm closing this as it's not a scirpy bug. 

If you have other questions, please also check out our new community discourse at https://discourse.scverse.org .

**Closed by grst** 2022-05-25 16:39 UTC
