### ISSUE TITLE
Tutorials for integrating BCR or TCR analysis with muon

### ISSUE THREAD

**Issue by zenghk** [scverse/scirpy#412] opened 2023-05-19 09:13 UTC
I am trying to using muon and scirpy for the analysis B cells scRNASeq with totalseq barcode.  But how to merge the result from muon (with rna and prot) with scirpy remain unknown, simply merge the mdata with vdj information fail to generate a full object for downstream analysis.

**Comment by grst** [comment] 2023-05-30 07:02
Hi @zenghk, 

I transferred this issue to the scirpy repository, as the problem is not related to muon. 

> , but the work failed while using ir.io.read_10x_vdj to read filtered_contig_annotations.csv, report a errors: AttributeError: no field named 'shape',

Could you please share the code snippet you are trying to execute, and the entire error message (including the full stacktrace). Then I'll look into it.

**Comment by zenghk** [comment] 2023-05-31 06:19
> 

I have solved this problem by  transferring the package into a virtual environment, previous error occur in python3.8, and I re-run the package successfully on python3.7. I think there is some conflict in some packages

**Comment by zenghk** [comment] 2023-05-31 06:55
> Hi @zenghk,
> 
> I transferred this issue to the scirpy repository, as the problem is not related to muon.
> 
> > , but the work failed while using ir.io.read_10x_vdj to read filtered_contig_annotations.csv, report a errors: AttributeError: no field named 'shape',
> 
> Could you please share the code snippet you are trying to execute, and the entire error message (including the full stacktrace). Then I'll look into it.

I re-started a new virtual environment and re-install all need package, this problem have been solved, I think the problem may be that some other related package is conflict with previous version or other package, but I cannot find out which package cause the problem, a new virtual environment may be recommended.

**Comment by grst** [comment] 2023-05-31 12:37
Ok, glad you found a solution. 

Are you still having issues related to running scirpy in combination with MuData/muon?

**Comment by grst** [comment] 2023-07-24 18:09
Closing this for now, let me know if there are futher issues!

**Closed by grst** 2023-07-24 18:09 UTC
