### ISSUE TITLE
Questions about combine gene expression and TCR expression

### ISSUE THREAD

**Issue by GouQiao** [scverse/scirpy#314] opened 2021-12-20 05:23 UTC
Hi,

I want to analyze scTCR after processing of Seurat. During Seurat, i will merge two samples in one object. Then I want to convert seurat object into h5ad anndata to perform TCR analysis by scirpy.  
But how can I combine merged gene expression and individual TCR information? Is this possible? or I have to firstly combine gene and TCR,  change to seurat, then back to h5ad for TCR analysis??  (Because I met problem when I change h5ad to seurat...)

Thanks.

**Comment by grst** [comment] 2021-12-20 07:52
I'm not sure if I got what the problem is here... 

So you are loading Expression data from multiple individuals that you combined in Seurat and then want to add the TCR information in scirpy? 

You are writing "individual TCR information", so is it important for you to analyse every patient individually, or are you just looking for how to combine the TCR information from all individuals with your (merged) expression data from Seurat?

**Comment by GouQiao** [comment] 2021-12-20 08:02
> I'm not sure if I got what the problem is here...
> 
> So you are loading Expression data from multiple individuals that you combined in Seurat and then want to add the TCR information in scirpy?
> 
> You are writing "individual TCR information", so is it important for you to analyse every patient individually, or are you just looking for how to combine the TCR information from all individuals with your (merged) expression data from Seurat?

> So you are loading Expression data from multiple individuals that you combined in Seurat and then want to add the TCR information in scirpy?
Yes!! I merged the transcriptome data in Seurat, then I want to combine TCR information with the merged seurat object. But TCR data is individual for each group....Is there a way to combine individual TCR data with merged seurat object??? Or from the beginning I should combine TCR data with transcriptome data individually, then I merge for seurat analysis?

**Comment by grst** [comment] 2021-12-20 08:09
> Is there a way to combine individual TCR data with merged seurat object. Or from the beginning I should combine TCR data with transcriptome data individually, then I merge for seurat analysis?

In principle, both should work! You can do so with the `anndata.concat` and `scirpy.io.merge_with_ir` functions as descirbed in the [data loading tutorial](https://icbi-lab.github.io/scirpy/latest/tutorials/tutorial_io.html#Combining-multiple-samples). 

There is one slight advantage of this strategy: 
> the beginning I should combine TCR data with transcriptome data individually, then I merge for seurat analysis

It could happen that cell barcodes are not unique between samples. Scanpy (and I guess seurat has a similar strategy) solves this by appending a `-1` to those cells barcodes. This could lead to an issue matching those cells between the TCR data and the expression data.

**Comment by GouQiao** [comment] 2021-12-20 09:37
> Thank you!
If it is possible, how to combine individual TCR data with merged seurat object?

**Comment by grst** [comment] 2022-05-18 15:36
Hi @GouQiao, 

if this is still relevant, please ask this (or other) questions in the [scverse community forum](https://discourse.scverse.org/). This is now our primary channel for supporting users. 

Cheers, 
Gregor

**Closed by grst** 2022-05-18 15:36 UTC
